name: test-reactpress
on: [pull_request]

jobs:
  test:
    name: Test ReactPress
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.8.1"
          cache: "npm"
      - run: yarn install --frozen-lockfile
      - run: yarn test
